### ISSUE TITLE
Bash is not always located at `/bin`

### ISSUE THREAD

**Issue by CreativeCactus** [mortend/xbash#1]
https://github.com/mortend/xbash/blob/b877095c877ac525db84a7a8e6b578d1d46fa1a2/index.js#L59

Ideally `/usr/bin/env bash` should be used, or if you don't mind making a syscall, you could run `which bash`.

This prevents installation of depending packages on NixOS, for example.

**Comment by mortend** [comment]
Thanks for the tip!

**Comment by mortend** [comment]
Fixed in `v1.6.0`.
